### ISSUE TITLE
Having issues with "invalid file path error"

### ISSUE THREAD

**Issue by LuckyTortoise** [Ulferno/upload-to-roblox#1]
Hi,
I have set up my ROBLOX CI to auto publish my game when the main branch has been pushed.
```
# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      - name: upload-to-roblox
        uses: Ulferno/upload-to-roblox@v1.0.0
        with:
          api-key: ${{ secrets.ROBLOX_API_KEY }}
          universeId: [PRIVATE]
          placeId: [PRIVATE]
          file: build.rbxl
          shouldPublish: true 
```
The issue is that it constantly says "invalid file path error"
The main.yml file is in project/.github/workflows
While the build file is in project

Error logs:
```
2021-11-12T04:41:22.5785617Z Uploading to Roblox
2021-11-12T04:41:22.8730230Z (node:2097) UnhandledPromiseRejectionWarning: Error: Request failed with status code 401
2021-11-12T04:41:22.8732025Z     at createError (/home/runner/work/_actions/Ulferno/upload-to-roblox/v1.0.0/node_modules/axios/lib/core/createError.js:16:15)
2021-11-12T04:41:22.8733201Z     at settle (/home/runner/work/_actions/Ulferno/upload-to-roblox/v1.0.0/node_modules/axios/lib/core/settle.js:17:12)
2021-11-12T04:41:22.8734678Z     at IncomingMessage.handleStreamEnd (/home/runner/work/_actions/Ulferno/upload-to-roblox/v1.0.0/node_modules/axios/lib/adapters/http.js:293:11)
2021-11-12T04:41:22.8735669Z     at IncomingMessage.emit (events.js:215:7)
2021-11-12T04:41:22.8736246Z     at endReadableNT (_stream_readable.js:1184:12)
2021-11-12T04:41:22.8737282Z     at processTicksAndRejections (internal/process/task_queues.js:80:21)
2021-11-12T04:41:22.8738673Z (node:2097) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 2)
2021-11-12T04:41:22.8740668Z (node:2097) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```

**Comment by LuckyTortoise** [comment]
Ah I realized I needed to allow any IP to access the OpenCloud API key.
Is there a way to still have an IP whitelist as I'm not exactly comfortable with having anyone being able to use my API key.

**Comment by Ulferno** [comment]
I believe there is a public list of the GitHub actions IP addresses, however they change constantly. See https://docs.github.com/en/actions/using-github-hosted-runners/about-github-hosted-runners#ip-addresses.

**Comment by LuckyTortoise** [comment]
Ah alright thank you!
